#' Auto-Update Configuration
#' @details Reads \code{autoupdate.cfg} belonging to the OpenBeta Server by
#'   default.
#' @param path Path of DCS World installation
#' @return List of character and logical vectors; see examples
#' @export
#' @examples
#' \dontrun{
#' dcsworldr::autoupdate.cfg() %>% utils::str()
#' #> List of 10
#' #>  $ WARNING       : chr "DO NOT EDIT this file. You may break your install!"
#' #>  $ branch        : chr "openbeta"
#' #>  $ version       : chr "2.7.10.19473"
#' #>  $ timestamp     : chr "20220207-145447"
#' #>  $ arch          : chr "x86_64"
#' #>  $ lang          : chr "EN"
#' #>  $ modules       : chr "DEDICATED_SERVER"
#' #>  $ launch        : chr "bin/DCS.exe"
#' #>  $ launch_args   : chr [1:2] "--norender" "--server"
#' #>  $ no_auto_inject: logi TRUE
#' }
autoupdate.cfg <- function(path = openbeta_server.path()) {
  jsonlite::fromJSON(file.path(path, "autoupdate.cfg"))
}

#' Auto-Update Configuration for Dedicated Server
#' @param cfg List of auto-update configuration pairs
#' @return Logical \code{TRUE} if modules includes dedicated server
#' @export
#' @examples
#' \dontrun{
#' dcsworldr::cfg.is_dedicated_server()
#' #> [1] TRUE
#' }
cfg.is_dedicated_server <- function(cfg = autoupdate.cfg()) {
  cfg$modules %in% "DEDICATED_SERVER"
}
